import React, { useState } from "react"
import "./App.css"
import NextImageTimer from "./NextImageTimer"
import Container from 'react-bootstrap/Container'
import Row from 'react-bootstrap/Row'
import Col from 'react-bootstrap/Col'
import Button from 'react-bootstrap/Button'
import Image from 'react-bootstrap/Image'
import Toggle from 'react-toggle'
import "react-toggle/style.css"
import SocialShare from "./SocialShare"

const Constants = {
  imageSwitchDurationHumanSec: 3,
  imageSwitchDurationAISec: 4,
}


const images = [
  {
    img: 'https://pbs.twimg.com/media/FRm3uewVIAAcHGO?format=jpg&name=medium',
    is_human: false,
    prompt: 'cats singing',
    by: '@bakztfuture with DALL-E 2',
    url: 'https://www.saharmor.me',
  },
  {
    img: 'https://images.unsplash.com/photo-1648737966670-a6a53917ed19?ixlib=rb-1.2.1&ixid=MnwxMjA3fDF8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2340&q=80',
    is_human: true,
    by: '@jgrishey on Unsplash',
    url: 'https://www.saharmor.me',
  },
  {
    img: 'https://pbs.twimg.com/media/FRwqFOpUUAEUMZq?format=jpg&name=medium',
    is_human: false,
    prompt: 'avocado armchair',
    by: '@bakztfuture with DALL-E 2',
    url: 'https://www.saharmor.me',
  },
  {
    img: 'https://images.unsplash.com/photo-1651454060241-a218f790be13?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2342&q=80',
    is_human: true,
    by: '@mattxfotographs on Unsplash',
    url: 'https://www.saharmor.me',
  }
].sort(() => Math.random() - 0.5)

const App = () => {
  const [score, setScore] = useState(0);
  const [currImgIdx, setCurrImgIdx] = useState(0);
  const [isTimerActive, setIsTimerActive] = useState(false);
  const [isCorrect, setIsCorrect] = useState(false);
  const [isFastMode, setIsFastMode] = useState(false);


  function getImageSwitchDuration() {
    if (isFinished()) {
      return 0
    }
    var tempTimeout = images[currImgIdx]["is_human"] ? Constants.imageSwitchDurationHumanSec : Constants.imageSwitchDurationAISec
    if (isFastMode) {
      return Math.floor(tempTimeout / 2)
    }
    return tempTimeout
  }


  function changeImage() {
    setIsTimerActive(true)
    return new Promise(res => setTimeout(function () {
      setCurrImgIdx(previousValue => ++previousValue)
      setIsCorrect(false)
      setIsTimerActive(false)
    }, getImageSwitchDuration() * 1000)
    );
  }

  async function handleClick(btnName) {
    if (isTimerActive) {
      return
    }

    if ((images[currImgIdx]["is_human"] && btnName === "human") || (!images[currImgIdx]["is_human"] && btnName === "robot")) {
      // correct
      setScore(previousValue => ++previousValue)
      setIsCorrect(true)
    } 
    
    await changeImage()
  }

  function renderPostClick() {
    return (
      <Row className={`${isTimerActive ? "visible" : "invisible"} pt-2"`}>
        <span className="text-muted small">By <a href={images[currImgIdx]['url']} target="_blank" rel="noopener noreferrer">{images[currImgIdx]["by"]}</a></span>
        {!images[currImgIdx]["is_human"] && <span className="text-muted small">Prompt: {images[currImgIdx]["prompt"]}</span>}

        {isTimerActive && <NextImageTimer seconds={getImageSwitchDuration()} />}
        {!isTimerActive && <h4>easter egg is back</h4>}
      </Row>
    )
  }

  function isFinished() {
    return currImgIdx >= images.length
  }

  function toggleFastMode() {
    setIsFastMode(previousValue => !previousValue)
  }

  return (
    <Container className="text-center justify-content-center align-items-center" fluid="md">
      <Row className="pt-4">
        <Col className="text-center"><span className="fs-1">This Image Does Not Exist</span></Col>
      </Row>
      <Row className="pt-1 pb-3">
        <Col className="text-center"><span className="fs-6 text-secondary">Can you tell if an image was generated by a human or a machine?</span></Col>
      </Row>

      {!isFinished() &&
        <Row className="justify-content-center align-items-center pb-2 py-4" xs={12} md={6} lg={6} sm={4}>
          <Col>
            <span className="small pe-2">Fast mode</span>
            <Toggle id='fast-mode' defaultChecked={isFastMode} onChange={toggleFastMode} />
          </Col>
        </Row>
      }


      {isFinished() && <Row className="justify-content-center text-center">
        <Col xs={12}>Done! Your score: <h1 className="text-success">{score}</h1></Col>
        <Col xs={12}>Challenge your friends&nbsp;
          <SocialShare url={"https://thisimagedoesnotexist.com"} title={`Can you tell if an image was generated by a human or a machine? I scored ${score}!`} />
        </Col>
      </Row>
      }

      {!isFinished() && <Container>
        <Row className="justify-content-center">
          <Col>
            <Image src={images[currImgIdx]["img"]} className="img-fluid rounded mx-auto d-block shadow" style={{ height: '18rem' }} alt="Generated art" />
          </Col>
        </Row>

        {!isFinished() &&
          <Row className="pt-2 justify-content-center">
            <Col>
              <span className={`${isCorrect ? "text-success fw-bolder fs-4" : ""}`}>Score: {score}</span>
            </Col>
          </Row>
        }

        <Row className="justify-content-center">
          <Col lg={2} md={3} xs={4} sm={3}><Button className="btn-xlarge" disabled={isTimerActive && images[currImgIdx]["is_human"]} variant="outlined" onClick={() => handleClick('robot')}><span role="img" aria-label="robot">🤖</span></Button></Col>
          <Col lg={2} md={3} xs={4} sm={3}><Button className="btn-xlarge" disabled={isTimerActive && !images[currImgIdx]["is_human"]} variant="outlined" onClick={() => handleClick('human')}><span role="img" aria-label="human">👩‍🎨</span></Button></Col>
        </Row>
        {renderPostClick()}
      </Container>
      }
      <Row className="mt-3 justify-content-center text-center">
        <hr className="hr"></hr>
      </Row>

      <Row>
        <span className="small text-secondary">Created by <a href="https://saharmor.me/?utm_source=thisimagedoesnotexist.com" target="_blank" rel="noopener noreferrer">Sahar</a> to increase awareness</span>
      </Row>
      <Row>
        <span className="small text-secondary">Images generated by <a href="https://openai.com/dall-e-2/?utm_source=thisimagedoesnotexist.com" target="_blank" rel="noopener noreferrer">DALL-E 2</a> and VQGAN generative models</span>
      </Row>
    </Container>
  );
}

export default App
